# Travis CI configuration

language: php
php:
  - 7.2
  - 7.3

before_script:
  - travis_retry composer self-update
  - travis_retry composer update --prefer-stable --no-interaction --prefer-source
  - travis_retry composer du -o

script:
  - php vendor/bin/phpunit
